### ISSUE TITLE
Oops! uninitialized constant ActiveSupport::Autoload

### ISSUE THREAD

**Issue by parkr** [kdaigle/hookable#1]
Hi! I clicked the `Deploy to Heroku` button in the README, added the webhook and saw this in the logs. Looks like we need another dependency or to love ActiveSupport to a different version?

```text
2015-11-24T20:03:31.202165+00:00 heroku[web.1]: Starting process with command `bundle exec rackup config.ru -p 57013`
2015-11-24T20:03:33.989823+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>': uninitialized constant ActiveSupport::Autoload (NameError)
2015-11-24T20:03:33.989852+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
2015-11-24T20:03:33.989853+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/number_helper.rb:1:in `<top (required)>'
2015-11-24T20:03:33.989854+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/core_ext/numeric/conversions.rb:2:in `require'
2015-11-24T20:03:33.989855+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
2015-11-24T20:03:33.989856+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/core_ext/numeric.rb:3:in `require'
2015-11-24T20:03:33.989856+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/core_ext/numeric.rb:3:in `<top (required)>'
2015-11-24T20:03:33.989857+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/core_ext.rb:2:in `require'
2015-11-24T20:03:33.989858+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
2015-11-24T20:03:33.989858+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/core_ext.rb:1:in `each'
2015-11-24T20:03:33.989859+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.1.6/lib/active_support/core_ext.rb:1:in `<top (required)>'
2015-11-24T20:03:33.989864+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/mongo_mapper-0.13.0/lib/mongo_mapper.rb:3:in `<top (required)>'
2015-11-24T20:03:33.989860+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/mongo_mapper-0.13.0/lib/mongo_mapper.rb:3:in `require'
2015-11-24T20:03:33.989864+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `require'
2015-11-24T20:03:33.989865+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
2015-11-24T20:03:33.989866+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `each'
2015-11-24T20:03:33.989866+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:72:in `block in require'
2015-11-24T20:03:33.989867+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `each'
2015-11-24T20:03:33.989867+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler/runtime.rb:61:in `require'
2015-11-24T20:03:33.989868+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/bundler-1.9.7/lib/bundler.rb:134:in `require'
2015-11-24T20:03:33.989869+00:00 app[web.1]: 	from /app/hookable.rb:3:in `<top (required)>'
2015-11-24T20:03:33.989869+00:00 app[web.1]: 	from /app/config.ru:1:in `require'
2015-11-24T20:03:33.989870+00:00 app[web.1]: 	from /app/config.ru:1:in `block in <main>'
2015-11-24T20:03:33.989870+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
2015-11-24T20:03:33.989871+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
2015-11-24T20:03:33.989872+00:00 app[web.1]: 	from /app/config.ru:in `new'
2015-11-24T20:03:33.989873+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
2015-11-24T20:03:33.989872+00:00 app[web.1]: 	from /app/config.ru:in `<main>'
2015-11-24T20:03:33.989874+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
2015-11-24T20:03:33.989874+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
2015-11-24T20:03:33.989875+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
2015-11-24T20:03:33.989876+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
2015-11-24T20:03:33.989876+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
2015-11-24T20:03:33.989879+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/bin/rackup:4:in `<top (required)>'
2015-11-24T20:03:33.989877+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:250:in `start'
2015-11-24T20:03:33.989878+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:141:in `start'
2015-11-24T20:03:33.989879+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in `load'
2015-11-24T20:03:33.989880+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in `<main>'
2015-11-24T20:03:35.232330+00:00 heroku[web.1]: Process exited with status 1
2015-11-24T20:03:35.254823+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by parkr** [comment]
Ah, I see @kdaigle isn't watching this repository. Kyle, should I close and patch on my own?

**Comment by kdaigle** [comment]
@parkr ha! Sorry, sometimes I mess up my repositories while testing (I likely was watching and un-watching to get some test events). :scream: 

If you're up for submitting a PR, I'd gladly accept it. Otherwise, I'll take a look sometime this week and get it fixed. (Thanks for the direct ping too to make me aware.)
